# Generated by Django 4.1.4 on 2022-12-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toost', models.CharField(max_length=120)),
                ('test', models.IntegerField()),
                ('tust', models.CharField(max_length=120)),
            ],
        ),
    ]
