# Generated by Django 4.1.4 on 2022-12-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='toost',
            new_name='tast',
        ),
    ]
