# Generated by Django 4.1.4 on 2022-12-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0002_rename_toost_testmodel_tast'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='tast_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='tast_ua',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='tust_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='tust_ua',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
