# Generated by Django 4.1.4 on 2022-12-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0003_testmodel_tast_en_testmodel_tast_ua_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='tast_ua',
            new_name='tast_uk',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='tust_ua',
            new_name='tust_uk',
        ),
    ]
