# Generated by Django 4.1.4 on 2022-12-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0004_rename_tast_ua_testmodel_tast_uk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='error`s short name')),
                ('full_text', models.CharField(max_length=255, verbose_name='error`s full text')),
                ('full_text_uk', models.CharField(max_length=255, null=True, verbose_name='error`s full text')),
                ('full_text_en', models.CharField(max_length=255, null=True, verbose_name='error`s full text')),
            ],
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='tast',
            field=models.CharField(max_length=120, verbose_name='tast'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='tast_en',
            field=models.CharField(max_length=120, null=True, verbose_name='tast'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='tast_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='tast'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='test',
            field=models.IntegerField(verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='tust',
            field=models.CharField(max_length=120, verbose_name='tust'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='tust_en',
            field=models.CharField(max_length=120, null=True, verbose_name='tust'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='tust_uk',
            field=models.CharField(max_length=120, null=True, verbose_name='tust'),
        ),
    ]
