# Generated by Django 4.1.4 on 2022-12-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0005_errormessages_alter_testmodel_tast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormessages',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='error`s short name'),
        ),
    ]
