# Generated by Django 4.1.4 on 2022-12-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0006_alter_errormessages_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='error`s short name')),
                ('full_text', models.CharField(max_length=255, verbose_name='error`s full text')),
            ],
        ),
    ]
