# Generated by Django 4.1.4 on 2022-12-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0007_infomessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomessages',
            name='full_text_en',
            field=models.CharField(max_length=255, null=True, verbose_name='message`s full text'),
        ),
        migrations.AddField(
            model_name='infomessages',
            name='full_text_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='message`s full text'),
        ),
        migrations.AlterField(
            model_name='infomessages',
            name='full_text',
            field=models.CharField(max_length=255, verbose_name='message`s full text'),
        ),
        migrations.AlterField(
            model_name='infomessages',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='message`s short name'),
        ),
    ]
