# Generated by Django 4.1.4 on 2022-12-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notifications_interval',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
