# Generated by Django 4.1.4 on 2022-12-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0011_project_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='users',
        ),
    ]
