# Generated by Django 4.1.4 on 2022-12-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0012_rename_user_id_project_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='vid_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
