# Generated by Django 4.1.4 on 2022-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0013_note_is_done_note_vid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
