# Generated by Django 4.1.4 on 2022-12-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0014_alter_note_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
