# Generated by Django 4.1.4 on 2022-12-21 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Self_Help', '0015_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('text', models.CharField(max_length=1000, null=True)),
                ('vid_id', models.CharField(max_length=50, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('project_id', models.ManyToManyField(to='Self_Help.project')),
            ],
        ),
    ]
