# Generated by Django 4.1.4 on 2022-12-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0016_project_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
