# Generated by Django 4.1.4 on 2022-12-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0022_alter_note_slug_alter_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_host',
            new_name='host',
        ),
    ]
