# Generated by Django 4.1.4 on 2023-06-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Self_Help', '0023_rename_project_host_project_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
